name: Setup
description: Sets up Node.js, pnpm, Foundry, and installs dependencies
runs:
  using: "composite"
  steps:
    - name: Check out the repo
      uses: actions/checkout@v4

    - name: Install Foundry
      uses: foundry-rs/foundry-toolchain@v1.4.0

    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 10.13.0

    - name: Install NodeJS
      uses: actions/setup-node@v4
      with:
        node-version: lts/Iron
        cache: pnpm

    - name: Install dependencies
      run: pnpm install -r --frozen-lockfile
